---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository
      tags: always
      apt:
        update_cache: yes
      changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: backend
  become: true
  vars_files:
    - vars/nodejs.yml
    - vars/nginx.yml
    - vars/domain.yml
  roles:
    - nodejs
    - nginx
    - domains
  tasks:
    - name: Install pm2
      npm: name=pm2 global=yes production=yes
