---
# - hosts: all
#   roles:
#     - base

- hosts: all
  become: true
  pre_tasks:
    - name: update repository
      tags: always
      apt:
        update_cache: yes
      changed_when: false

- hosts: backend
  become: true
  vars_files:
    - vars/nodejs.yml
    - vars/nginx.yml
    - vars/domain.yml
    - vars/mysql.yml
  roles:
    - nodejs
    - nginx
    - mysql
    - domains
  tasks:
    - name: Install pm2
      npm: name=pm2 global=yes production=yes
    - name: Install yarn
      npm: name=yarn global=yes production=yes
    - name: Install nestjs
      npm: name=@nestjs/cli global=yes production=yes
