---
# Nginx copy config.
- name: Copy nginx server configuration in place.
  template:
    src: "app.conf.j2"
    dest: "/etc/nginx/conf.d/{{ domain_app_name }}.conf"
    owner: root
    mode: 0644
  notify:
    - reload nginx

- name: Copy nginx client configuration in place.
  template:
    src: "client.conf.j2"
    dest: "/etc/nginx/conf.d/{{ domain_client_name }}.conf"
    owner: root
    mode: 0644
  notify:
    - reload nginx
