---
# Nginx copy config.
- name: Copy nginx configuration in place.
  template:
    src: "app.conf.j2"
    dest: "/etc/nginx/conf.d/{{ app_name }}"
    owner: root
    mode: 0644
  notify:
    - reload nginx
